---
# tasks file for roles/trove
- name: Included var from controller_required
  include_vars:
    file: ../../{{ item }}/defaults/main.yml
  with_items:
    - controller_required
    - keystone
    - compute
    - cinder
  when:
    - in_action == 'controller'
  tags: ['copy_script']

- name: Copy trove script to remote
  template:
    dest: '{{ dest_scripts }}/trove.sh'
    force: yes
    mode: 0755
    src: controller.sh.j2
  when:
    - in_action == 'controller'
  tags: ['copy_script']

- name: Installing trove service
  shell: sh trove.sh
  args:
    chdir: '{{ dest_scripts }}'
  when:
    - in_action == 'controller'
  tags: ['install_trove']