---
# defaults file for roles/keystone

database_keystone_password: Welcome123

keystone:
  password: Welcome123
  admin_url: 192.168.53.89:5000
  internal_url: 192.168.53.89:5000
  public_url: 192.168.53.89:5000

domains:
  - name: example
    description: An Example Domain


projects:
  - name: service
    domain: default
    description: Service Project
  - name: myproject
    domain: default
    description: Demo Project

users:
  - name: myuser
    password: Welcome123
    domain: default

openstack_roles:
  - name: onwer_project
    assign:
      - user: myuser
        project: myproject